### Modifikasi Data Agar Memenuhi Kriteria

import modul

In [42]:
import pandas as pd
import numpy as np
import matplotlib as plt

load dataset

In [43]:
path_sample = "../dataset/original_sample.csv"
df = pd.read_csv(path_sample)

df.head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

Missing Value
- Hapus secara acak beberapa nilai pada kolom tertentu (misal Units_Sold atau Avg_Price_EUR)

In [44]:
df.loc[df.sample(frac=0.002).index, 'Region'] = np.nan

In [45]:
df.loc[df.sample(frac=0.002).index, 'Units_Sold'] = np.nan

cek missing value

In [46]:
df.isnull().sum()

Year                0
Month               0
Region              6
Model               0
Units_Sold          6
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

cek outlier
- Ubah beberapa nilai menjadi sangat ekstrem (misal 10 kali lipat dari nilai normal)

In [47]:
df.loc[df.sample(frac=0.001).index, 'Revenue_EUR'] = df['Revenue_EUR'].max() * 10

Cek Tipe tidak konsisten
- Ubah beberapa baris pada kolom Month menjadi teks (misal "Jan"). mengganti sebagian nilai yang memang bernilai 1 menjadi 'Jan', maka sampling harus dilakukan hanya pada baris yang Month == 1. Langkahnya: Ambil baris yang Month == 1, Dari baris itu ambil sebagian secara acak dan Ganti menjadi 'Jan'

In [48]:
idx = df[df['Month'] == 1].sample(frac=0.3).index
df.loc[idx, 'Month'] = 'Jan'

print(idx)

Index([1543,  795, 1951, 1921, 1164, 1179, 1934, 1932,  402,  394, 1560, 1170,
       2705, 1564,  408,  404, 1172,    0, 2308, 1540, 2708,  770,  405, 1922,
        775, 1559,   28, 1929, 2326, 1544,  787, 1157, 1557, 2319,  768,  388,
        783,  779, 2714,   24,   12, 1152, 2700, 2699,  413, 2718,    5, 1948,
       2688, 2314, 2691, 1553,   31, 2331, 2312, 1563, 2304,   27, 2703, 1536,
       1176, 2689,  776, 2329, 1168, 1155, 1942,   15, 1539, 2717, 1930, 2335,
       2316, 1161, 2322, 1943, 2334],
      dtype='int64')

C:\Users\Pongo\AppData\Local\Temp\ipykernel_19724\2155556184.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Jan' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[idx, 'Month'] = 'Jan'

Cek Duplikasi
- Gandakan beberapa baris dan tambahkan ke dataframe

In [49]:
# Ambil sample acak 10 baris data, random state biar data nya tidak berubah ubah yang di pick tiap re run.
duplicates = df.sample(n=20, random_state=42)
df = pd.concat([df, duplicates], ignore_index=True)

print(duplicates)

      Year Month       Region     Model  Units_Sold  Avg_Price_EUR  \
2696  2025     1        China  3 Series      3533.0          46381
1756  2022     7  RestOfWorld        X7      4856.0          91502
2528  2024     8       Europe  3 Series      3340.0          46043
194   2018     7       Europe        X3      8255.0          58397
240   2018     8          USA  3 Series     10610.0          48597
2788  2025     4       Europe        X7     12213.0          92457
2007  2023     3          USA      MINI     10245.0          42694
2028  2023     4        China        X7      7559.0          90212
1874  2022    11          USA        X3     10258.0          59936
1910  2022    12          USA        iX      7092.0          73773
2566  2024     9       Europe        iX     14802.0          73234
2591  2024     9  RestOfWorld      MINI     13763.0          42241
535   2019     5          USA      MINI      6787.0          41339
2977  2025    10       Europe  5 Series      3036.0          60966
457   2019     3        China  5 Series      8884.0          63255
266   2018     9        China        X3      9702.0          58713
2969  2025     9  RestOfWorld  5 Series      9870.0          61507
102   2018     4       Europe        iX      3401.0          74119
1640  2022     4        China  3 Series     12227.0          46824
2111  2023     6  RestOfWorld      MINI      7443.0          42122

      Revenue_EUR  BEV_Share  Premium_Share  GDP_Growth  Fuel_Price_Index
2696    163864073      0.184          15.20        2.30              1.34
1756    444333712      0.128           6.64        2.64              1.19
2528    153783620      0.177          15.31        3.43              1.33
194     482067235      0.013          14.62        2.18              0.98
240     515614170      0.022          18.34        3.34              0.99
2788   1129177341      0.197          15.08        3.72              1.36
2007    437400030      0.128          16.61        1.95              1.23
2028    681912508      0.166          19.18        3.10              1.22
1874    614823488      0.118          18.17        1.93              1.25
1910    523198116      0.118          14.20        4.51              1.22
2566   1084009668      0.162          16.27        1.27              1.25
2591    581362883      0.178           5.82        2.76              1.32
535     280567793      0.040          18.70        2.25              1.07
2977    185092776      0.213          19.10        4.06              1.38
457     561957420      0.050          18.80        2.52              0.98
266     569633526      0.013          20.39        2.56              1.00
2969    607074090      0.200           6.64        3.40              1.35
102     252078719      0.019          14.60        3.55              0.96
1640    572517048      0.112          17.20        2.43              1.18
2111    313514046      0.152           5.82        1.42              1.27

In [50]:
df.duplicated().sum()

np.int64(20)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3092 entries, 0 to 3091
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3092 non-null   int64
 1   Month             3092 non-null   object
 2   Region            3086 non-null   object
 3   Model             3092 non-null   object
 4   Units_Sold        3086 non-null   float64
 5   Avg_Price_EUR     3092 non-null   int64
 6   Revenue_EUR       3092 non-null   int64
 7   BEV_Share         3092 non-null   float64
 8   Premium_Share     3092 non-null   float64
 9   GDP_Growth        3092 non-null   float64
 10  Fuel_Price_Index  3092 non-null   float64
dtypes: float64(5), int64(3), object(3)
memory usage: 265.8+ KB

In [52]:
df['Month'].unique()

array(['Jan', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype=object)

In [53]:
df[df['Month'] == 'Jan'].head()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,Jan,Europe,3 Series,7822.0,47482,371404204,0.011,19.12,3.50,1.00
5,2018,Jan,Europe,i4,10607.0,64082,679717774,0.035,19.12,3.50,1.00
12,2018,Jan,China,X7,9119.0,90034,821020046,0.020,17.60,2.37,1.02
15,2018,Jan,China,MINI,6025.0,43893,264455325,0.031,17.60,2.37,1.02
24,2018,Jan,RestOfWorld,3 Series,10121.0,47485,480595685,-0.000,6.28,4.18,0.97

Save

In [54]:
output_path = '../dataset/bmw_global_sales_2018_2025.csv'
df.to_csv(output_path, index=False)
print("Data file sudha berhasil disimpan di path ", output_path)

Data file sudha berhasil disimpan di path  ../dataset/bmw_global_sales_2018_2025.csv